
export const UPDATE_ALL_GAMES = "UPDATE_ALL_GAMES";
export const UPDATE_CURRENT_GAME = "UPDATE_CURRENT_GAME";
export const UPDATE_CONSOLE = "UPDATE_CONSOLE";
export const UPDATE_CURRENT_CONSOLE = "UPDATE_CURRENT_CONSOLE";
export const UPDATE_GAME = "UPDATE_GAME";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const UPDATE_CURRENT_GENRE = "UPDATE_CURRENT_GENRE";
export const UPDATE_GENRE = "UPDATE_GENRE";




export const CLEAR_CART = "CLEAR_CART";




