export const UPDATE_ALL_GAMES = "UPDATE_ALL_GAMES";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_GAME = "UPDATE_GAME";
export const UPDATE_CURRENT_GAME = "UPDATE_CURRENT_GAME";
